name: WebAPI
main: mc.battleplugins.webapi.WebAPI
<<<<<<< HEAD
version: 0.1.0
=======
version: 0.0.4
>>>>>>> 42838ed08f066e3becbe13c2e1bd2cc9335cb29b
description: A plugin tool for providing URL connections in an organized and proper manner.
authors: [lDucks, alkarinv]
website: http://BattlePlugins.com
