name: WebAPI
main: mc.battleplugins.webapi.WebAPI
version: 0.1.0
description: A plugin tool for providing URL connections in an organized and proper manner.
authors: [lDucks, alkarinv]
website: http://BattlePlugins.com
