name: WebAPI
main: com.battleplugins.webapi.WebAPI
version: 0.0.0
description: A plugin tool for providing URL connections in an organized and proper manner.
authors: [lDucks, alkarinv]
website: http://BattlePlugins.com
